-- ============================================================
-- Broadcasting Event — Initial Schema
-- ============================================================
-- Run this in the Supabase SQL Editor or via `supabase db push`

-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================================
-- Profiles (extends Supabase auth.users)
-- ============================================================
CREATE TABLE IF NOT EXISTS public.profiles (
  id          UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  username    TEXT UNIQUE NOT NULL,
  avatar_url  TEXT,
  created_at  TIMESTAMPTZ DEFAULT NOW()
);

-- Auto-create profile on new user signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, username)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'username', split_part(NEW.email, '@', 1))
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ============================================================
-- Streams
-- ============================================================
CREATE TABLE IF NOT EXISTS public.streams (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  creator_id        UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  title             TEXT NOT NULL,
  status            TEXT NOT NULL DEFAULT 'live' CHECK (status IN ('live', 'ended')),
  livekit_room_name TEXT UNIQUE NOT NULL,
  viewer_count      INT NOT NULL DEFAULT 0,
  started_at        TIMESTAMPTZ DEFAULT NOW(),
  ended_at          TIMESTAMPTZ
);

-- Increment viewer count
CREATE OR REPLACE FUNCTION public.increment_viewer_count(stream_id UUID)
RETURNS VOID AS $$
BEGIN
  UPDATE public.streams
  SET viewer_count = viewer_count + 1
  WHERE id = stream_id AND status = 'live';
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Decrement viewer count (floor at 0)
CREATE OR REPLACE FUNCTION public.decrement_viewer_count(stream_id UUID)
RETURNS VOID AS $$
BEGIN
  UPDATE public.streams
  SET viewer_count = GREATEST(viewer_count - 1, 0)
  WHERE id = stream_id AND status = 'live';
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ============================================================
-- Follows
-- ============================================================
CREATE TABLE IF NOT EXISTS public.follows (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  follower_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  creator_id  UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  created_at  TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(follower_id, creator_id)
);

-- ============================================================
-- Chat Messages
-- ============================================================
CREATE TABLE IF NOT EXISTS public.messages (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  stream_id        UUID NOT NULL REFERENCES public.streams(id) ON DELETE CASCADE,
  sender_id        UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  sender_username  TEXT NOT NULL,
  body             TEXT NOT NULL,
  client_timestamp TIMESTAMPTZ NOT NULL, -- original timestamp (preserves offline ordering)
  created_at       TIMESTAMPTZ DEFAULT NOW()
);

-- Index for ordered chat retrieval
CREATE INDEX IF NOT EXISTS messages_stream_id_client_ts_idx
  ON public.messages(stream_id, client_timestamp ASC);

-- ============================================================
-- Stream Metadata Log (for highlight detection)
-- ============================================================
CREATE TABLE IF NOT EXISTS public.stream_metadata_log (
  id                       UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  stream_id                UUID NOT NULL REFERENCES public.streams(id) ON DELETE CASCADE,
  recorded_at              TIMESTAMPTZ DEFAULT NOW(),
  viewer_count             INT NOT NULL DEFAULT 0,
  message_count_per_minute INT NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS stream_metadata_log_stream_idx
  ON public.stream_metadata_log(stream_id, recorded_at ASC);

-- ============================================================
-- Highlights (generated by n8n post stream-end)
-- ============================================================
CREATE TABLE IF NOT EXISTS public.highlights (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  stream_id   UUID NOT NULL REFERENCES public.streams(id) ON DELETE CASCADE,
  occurred_at TIMESTAMPTZ NOT NULL,
  reason      TEXT NOT NULL,
  created_at  TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- In-App Notifications (written by n8n, read by app)
-- ============================================================
CREATE TABLE IF NOT EXISTS public.notifications (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id    UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  title      TEXT NOT NULL,
  body       TEXT NOT NULL,
  read       BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS notifications_user_id_idx
  ON public.notifications(user_id, created_at DESC);

-- ============================================================
-- Daily Digests (generated by n8n daily cron)
-- ============================================================
CREATE TABLE IF NOT EXISTS public.daily_digests (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  digest_date  DATE NOT NULL UNIQUE,
  top_streams  JSONB NOT NULL DEFAULT '[]',
  created_at   TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- Row Level Security (RLS)
-- ============================================================

ALTER TABLE public.profiles          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.streams           ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.follows           ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stream_metadata_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.highlights        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_digests     ENABLE ROW LEVEL SECURITY;

-- Profiles: anyone can read, only owner can update
CREATE POLICY "profiles_select_all" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "profiles_update_own" ON public.profiles FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "profiles_insert_own" ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);

-- Streams: anyone can read live streams; only creator can insert/update
CREATE POLICY "streams_select_all" ON public.streams FOR SELECT USING (true);
CREATE POLICY "streams_insert_own" ON public.streams FOR INSERT WITH CHECK (auth.uid() = creator_id);
CREATE POLICY "streams_update_own" ON public.streams FOR UPDATE USING (auth.uid() = creator_id);

-- Follows: anyone can read; auth users can insert/delete their own
CREATE POLICY "follows_select_all"  ON public.follows FOR SELECT USING (true);
CREATE POLICY "follows_insert_own"  ON public.follows FOR INSERT WITH CHECK (auth.uid() = follower_id);
CREATE POLICY "follows_delete_own"  ON public.follows FOR DELETE USING (auth.uid() = follower_id);

-- Messages: anyone in stream can read; auth users can insert
CREATE POLICY "messages_select_all"   ON public.messages FOR SELECT USING (true);
CREATE POLICY "messages_insert_auth"  ON public.messages FOR INSERT WITH CHECK (auth.uid() = sender_id);

-- Stream metadata: service role writes (edge function), anyone reads
CREATE POLICY "metadata_select_all"  ON public.stream_metadata_log FOR SELECT USING (true);
CREATE POLICY "metadata_insert_auth" ON public.stream_metadata_log FOR INSERT WITH CHECK (auth.uid() IS NOT NULL);

-- Highlights: anyone can read
CREATE POLICY "highlights_select_all" ON public.highlights FOR SELECT USING (true);

-- Notifications: only the recipient can read their own
CREATE POLICY "notifications_select_own" ON public.notifications FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "notifications_update_own" ON public.notifications FOR UPDATE USING (auth.uid() = user_id);

-- Daily digests: public read
CREATE POLICY "digests_select_all" ON public.daily_digests FOR SELECT USING (true);

-- ============================================================
-- Realtime: enable replication for live tables
-- ============================================================
ALTER PUBLICATION supabase_realtime ADD TABLE public.streams;
ALTER PUBLICATION supabase_realtime ADD TABLE public.messages;
ALTER PUBLICATION supabase_realtime ADD TABLE public.notifications;
